header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: thumbrise
    copyright-year: '2026'
    software-name: resilience

  paths:
    - '**/*.go'

  paths-ignore:
    - 'docs/**'
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/testdata/**'
    - '**/go.mod'
    - '**/go.sum'
    - '**/package-lock.json'
    - '**/node_modules/**'
    - 'LICENSE'
    - 'NOTICE'
    - '.gitignore'
    - '.releaserc.js'
    - 'release-template.hbs'

  comment: on-failure
  license-location-threshold: 80